<div id="add_aliancia">
	<?php if ($success == "Aliancia bola vytvorená.") :?>
		<p><?= $success ?></p>
	<?php else : ?>
		<?php if ($success != "") :?>
			<p><?= $success ?></p>
		<?php endif; ?>
		<form method="POST" action="home/add_aliancia" id="new_aliancia">
			<p>Názov aliancie<input type="text" name="nazov_aliancie" required></p>
			<p>Dátum vzniku<input type="datetime-local" name="datum_vzniku" required></p>
			<p>Famílie v aliancii: <?= $nazovFamilie; ?>
				<?php foreach($cartels as $cartel) : ?>
					<input type="checkbox" name="familie_v_aliancii[]" value="<?= $cartel["nazov_familie"]?>"><?= $cartel["nazov_familie"]?>
				<?php endforeach; ?>
			</p>
			<input type="submit" value="Založiť alianciu">
		</form>
	<?php endif; ?>
</div>