<div id="buddies_stranka">
	<div id="search_container">
		<form method="POST" action="buddies/search" id="search">
			<p class="search">Vyhľadať osobu</p>
			<input type="text" name="hladana_osoba">
			<input type="submit" value="Hľadaj">
			<?php if (!empty($msg_hladanaOsoba)) : ?>
				<p id="chybova_hlaska"><?= $msg_hladanaOsoba ?></p> 
			<?php endif; ?>
		</form>
		<?php if($_SESSION["typ"] != 0) : //DON alebo ADMIN?>
			<form method="POST" action="buddies/new_buddy" id="add">
				<input type="submit" value="Pridať člena">
			</form>
		<?php endif; ?>
		<?php if($_SESSION["typ"] == 2) : //ADMIN?>
			<form method="POST" action="buddies/new_don" id="add">
				<input type="submit" value="Pridať Dona">
			</form>
		<?php endif; ?>
	</div>
	<div id="osoby_result">		
		<table>
			<tr><th>Rodne cislo</th><th>Meno</th><th>Priezvisko</th><th>Vek</th><th>Don/Clen</th></tr>
			<?php if (($hladanaOsoba) != NULL) : ?>
				<?php if(count($hladanaOsoba) == 1 && $_SESSION["typ"] == 2) : //len jeden vysledok a prihlaseny je ADMIN?>
					<form method="POST" action="buddies/edit_person">
						<input type="hidden" name="rodne_cislo" value="<?= $hladanaOsoba[0]["rodne_cislo"]; ?>">
						<input type="submit" value="Editovať vybranú osobu">
					</form>
				<?php endif; ?>
				<?php foreach($hladanaOsoba as $persona) : ?>
					<tr>
						<td><?= $persona["rodne_cislo"] ?></td>
						<td><?= $persona["meno"] ?></td>
						<td><?= $persona["priezvisko"] ?></td>
						<td><?= $persona["vek"]?></td>
						<?php if ($persona["typ"] == 0): ?>
							<td>Člen</td>
						<?php else: ?>
							<td>Don</td>
						<?php endif; ?>
					</tr>
				<?php endforeach; ?>
			<?php endif; ?>
			<?php if (empty($hladanaOsoba)) : ?>
				<?php foreach($zoznamOsob as $persona) : ?>
					<tr>
						<?php if (($persona["meno"]) != "admin") : ?>
							<td><?= $persona["rodne_cislo"] ?></td>
							<td><?= $persona["meno"] ?></td>
							<td><?= $persona["priezvisko"] ?></td>
							<td><?= $persona["vek"]?></td>
							<?php if ($persona["typ"] == 0): ?>
								<td>Člen</td>
							<?php else: ?>
								<td>Don</td>
							<?php endif; ?>
						<?php endif; ?>
					</tr>
				<?php endforeach; ?>
			<?php endif; ?>
			<form action="/buddies" method="POST">
				<input type="submit" value="Celý zoznam">
			</form>
		</table>
	</div>	
</div>