<div>
	<?php if ($success != "") :?>
		<p><?= $success ?></p>
	<?php else: ?>
		<table>
			
				<tr><td>Rodne cislo: <?= $person[0]["rodne_cislo"]?></tr></td> 
				<tr><td>Meno: <?= $person[0]["meno"] ?></td></tr>
				<tr><td>Priezvisko:<?= $person[0]["priezvisko"]?></td></tr>
				<tr><td> Vek:<?= $person[0]["vek"]?></td></tr>
				<?php if($person[0]["typ"] == 0) : //upravujem Clena ?>
					<form method="POST">
						<td> Hodnost:
							<input type="hidden" name="rodne_cislo" value="<?= $person[0]["rodne_cislo"] ?>">
							<select name="hodnost">
								<option value="<?= $hodnost ?>" selected><?= $hodnost ?></option>
								<option value="zelenac">Zelenáč</option>				
								<option value="uklizec">Zametač</option>
								<option value="sofer">Šofér</option>
								<option value="kapsar">Zlodej</option>
								<option value="vymahac">Vymáhač</option>
								<option value="snajper">Snajper</option>
							</select>	
						</td>			
						<tr><td> Pokrvna vazba
							<input type="hidden" name="rodne_cislo" value="<?= $person[0]["rodne_cislo"] ?>">
							<?php if ($pokrvna_vazba == "ano") :?>
								<input type="radio" name="pokrvna_vazba" value="ano" checked required>áno
								<input type="radio" name="pokrvna_vazba" value="ne" required>nie
							<?php else : ?>
								<input type="radio" name="pokrvna_vazba" value="ano" required>áno
								<input type="radio" name="pokrvna_vazba" value="ne" checked required>nie
							<?php endif; ?>
						</td></tr>
						<input type="submit" value="Uložiť zmeny">
					</form>
				<?php else: //upravujem Dona?>
					<td><?= $nazov_familie." ".$aliancia?></td>
					<td><?=$zvolal_zraz?></td>
					<form method="POST">
						<td>
							<input type="hidden" name="rodne_cislo" value="<?= $person[0]["rodne_cislo"] ?>">
							<input type="text" list="uzemie" name="gps_uzemie" required>
							<datalist id="uzemie" autocomplete="off">
								<select>
									<option value="<?= $gps_uzemie?>" selected>Aktuálna</option>
									<?php foreach($uzemie as $miesto) : ?>
										<?php if ($miesto["gps"] != "admin") :?>
											<option value="<?= $miesto["gps"]?>"><?= $miesto["hodnota"]?></option>
										<?php endif; ?>
									<?php endforeach; ?>
								</select>				
							</datalist>
						</td>
						<input type="submit" value="Uložiť zmeny">
					</form>
				<?php endif; ?>
			</tr>
		</table>
	<?php endif; ?>
</div>