<div id="left">
	<?php if ($success != "") :?>
			<p><?= $success ?></p>
		<?php endif; ?>
	<?php if($_SESSION["typ"] == 1) : ?>
		<h1>DON</h1>
		<div id="aliancia">
			<table>
				<tr><th colspan="2">Tvoja aliancia</th></tr>
				<?php if ($aliancia->getIdAliancie() != NULL) : ?>
					<tr><td>Názov aliencie:</td><td><?= $aliancia->getNazovAliancie(); ?></td></tr>
					<tr>
						<td>Dátum vzniku aliancie:</td><td><?= $aliancia->getDatumVzniku(); ?></td>
						<form method="POST" action="home/zrusena_aliancia" id="del_aliancia">
							<td><input type="submit" value="Zrušiť alianciu"></td>
							<input type="hidden" name="del_aliancia" value="NULL">
						</form>
					</tr>
				<?php else : ?>
					<tr>
						<form method="POST" action="home/add_aliancia" id="new_aliancia">
							<td><input type="submit" value="Pridať alianciu"></td>
						</form>
					</tr>
				<?php endif; ?>
			</table>	
		</div>
<!-- 		<div id="zraz_donov">
			<table>
				<tr><th colspan="2">Zraz donov</th></tr>
				<?php if ($zraz_donov != NULL) : ?>
					<tr><td>Zraz číslo <?= $zraz_donov->getIdZrazu(); ?></td></tr>
					<tr><td>Usporiadateľ:</td><td>meno dona</td>
					<tr><td>Dátum a čas:</td><td><?= $zraz_donov->getDatumCas(); ?></td>
					<tr><td>Miesto zrazu:</td><td><?= $zraz_donov->getGpsMiesta(); ?></td>
					</tr>
				<?php else : ?>
					<tr><td>Žiadny zraz nie je naplanovaný.</td></tr>
				<?php endif; ?>
			</table>	
		</div> -->
	<?php else : ?>
		<h1>ČLEN</h1>
	<?php endif; ?>
	<div id="vypis_ulohy">
		<table>
			<tr><th colspan="2">Zadané ulohy</th></tr>
			<?php if(empty($ulohy)) : ?><tr><td>Žadne zadané úlohy</td><tr><?php endif; ?>
			<?php foreach($ulohy as $uloha) : ?>
				<tr><td><?= $uloha["specificke_meno"] ?></td></tr>
			<?php endforeach; ?>
		</table>
	</div>
	<div id="familia">
		<table>
			<tr><th colspan="2">Tvoja família</th></tr>
			<tr><td>Názov famílie: </td><td><?= $nazovFamilie ?></td></tr>
			<tr><td>Don: </td><td><?= $sefFamilie["meno"] . " " . $sefFamilie["priezvisko"] ?></td></tr>
			<?php if($_SESSION["typ"] == 1) : ?>
				<tr><td colspan="2">Členovia: </td></tr>
					<?php foreach($zoznamClenov as $clen) : ?> 
						<tr>
							<td><?= $clen["meno"] . " " . $clen["priezvisko"]?></td>
							<td>
								<form method="POST">
									<input type="hidden" name="rodne_cislo" value="<?= $clen["rodne_cislo"] ?>">
									<select name="hodnost">
										<option value="<?= $clen["hodnost"] ?>" selected><?= $clen["hodnost"] ?></option>
										<option value="zelenac">Zelenáč</option>				
										<option value="uklizec">Zametač</option>
										<option value="sofer">Šofér</option>
										<option value="kapsar">Zlodej</option>
										<option value="vymahac">Vymáhač</option>
										<option value="snajper">Snajper</option>
									</select>	
									<input type="submit" value="Uložiť">
								</form>
							</td>
						</tr>
					<?php endforeach; ?>
			<?php else : ?>
				<tr><td colspan="2">Členovia: </td></tr>
					<?php foreach($zoznamClenov as $clen) : ?> 
						<tr><td></td><td><?= $clen["meno"] . " " . $clen["priezvisko"] ?></td></tr>
					<?php endforeach; ?>
			<?php endif; ?>
		</table>
	</div>
</div>