<div id="left">
	<?php if($_SESSION["typ"] == 1) : ?>
		<h1>DON</h1>
		<?php if (isset($aliancia)) : ?>
			<div id="aliancia">
				<table>
					<tr><th colspan="2">Tvoja aliancia</th></tr>
					<tr><td>Názov aliencie:</td><td><?= $aliancia->getNazovAliancie(); ?></td></tr>
					<tr><td>Dátum vzniku aliancie:</td><td><?= $aliancia->getDatumVzniku(); ?></td></tr>
				</table>	
			</div>
		<?php endif; ?>
	<?php else : ?>
		<h1>ČLEN</h1>
	<?php endif; ?>
	<div id="vypis_ulohy">
		<table>
			<tr><th colspan="2">Zadané ulohy</th></tr>
			<?php if(empty($ulohy)) : ?><tr><td>Žadne zadané úlohy</td><tr><?php endif; ?>
			<?php foreach($ulohy as $uloha) : ?>
				<tr><td><?= $uloha["specificke_meno"] ?></td></tr>
			<?php endforeach; ?>
		</table>
	</div>
	<div id="familia">
		<table>
			<tr><th colspan="2">Tvoja família</th></tr>
			<tr><td>Názov famílie: </td><td><?= $nazovFamilie ?></td></tr>
			<tr><td>Don: </td><td><?= $sefFamilie["meno"] . " " . $sefFamilie["priezvisko"] ?></td></tr>
			<?php if($_SESSION["typ"] == 1) : ?>
				<tr><td colspan="2">Členovia: </td></tr>
					<?php foreach($zoznamClenov as $clen) : ?> 
						<tr>
							<td><?= $clen["meno"] . " " . $clen["priezvisko"]?></td>
							<td>
								<form method="POST">
									<input type="hidden" name="rodne_cislo" value="<?= $clen["rodne_cislo"] ?>">
									<select name="hodnost">
										<option value="<?= $clen["hodnost"] ?>" selected><?= $clen["hodnost"] ?></option>
										<option value="zelenac">Zelenáč</option>				
										<option value="uklizec">Zametač</option>
										<option value="sofer">Šofér</option>
										<option value="kapsar">Zlodej</option>
										<option value="vymahac">Vymáhač</option>
										<option value="snajper">Snajper</option>
									</select>	
									<input type="submit" value="Uložiť">
								</form>
							</td>
						</tr>
					<?php endforeach; ?>
			<?php else : ?>
				<tr><td colspan="2">Členovia: </td></tr>
					<?php foreach($zoznamClenov as $clen) : ?> 
						<tr><td></td><td><?= $clen["meno"] . " " . $clen["priezvisko"] ?></td></tr>
					<?php endforeach; ?>
			<?php endif; ?>
		</table>
	</div>
</div>