<div id="new_buddy">
	<?php if ($success != "") :?>
		<p><?= $success ?></p>
	<?php endif; ?>
	<form method="POST" action="buddies/new_buddy" id="add">
		<input type="hidden" name="nazov_familie" value="<?php echo $don->getNazovFamilie();?>" />
		<p>Meno<input type="text" name="meno" required></p>
		<p>Priezvisko<input type="text" name="priezvisko" required></p>
		<p>Rodné číslo<input type="text" name="rodne_cislo" required></p>
		<p>Vek<input type="number" name="vek" required></p>
		<p>Heslo<input type="text" name="heslo" required></p>
		<p>Hodnosť
			<input list="hodnost" name="hodnost">
			<datalist id="hodnost">
				<option value="" selected=""></option>
				<option value="zelenac"></option>				
				<option value="uklizec"></option>
				<option value="sofer"></option>
				<option value="kapsar"></option>
				<option value="vymahac"></option>
				<option value="snajper"></option>
			</datalist>
		</p>
		<p>
			Pokrvná väzba<input type="radio" name="pokrvna_vazba" value="ano" required>áno
			<input type="radio" name="pokrvna_vazba" value="ne" required>nie
		</p>
		<input type="submit" value="Pridať">
	</form>
</div>