<div id="new_don">
	<?php if ($success != "") :?>
		<p><?= $success ?></p>
	<?php endif; ?>
	<form method="POST" action="admin/new_don" id="add">
		<input type="hidden" name="typ" value="1" required></p>
		<div id="new_don_table">
			<table>
				<tr><td>Názov famílie<input type="text" name="nazov_familie" required></td></tr>
				<tr><td>GPS územia<input type="text" list="place" name="gps_uzemie" required>
					<datalist id="place" autocomplete="off">
						<select>
							<option value="" selected=""></option>
							<?php foreach($uzemia as $miesto) : ?>
								<?php if ($miesto["gps"] != "admin") :?>
									<option value="<?= $miesto["gps"]?>"><?= $miesto["hodnota"]?></option>
								<?php endif; ?>
							<?php endforeach; ?>
						</select>				
					</datalist>
				</td></tr>
				<tr><td>Meno<input type="text" name="meno" required></td></tr>
				<tr><td>Priezvisko<input type="text" name="priezvisko" required></td></tr>
				<tr><td>Rodné číslo<input type="text" name="rodne_cislo" required></td></tr>
				<tr><td>Vek<input type="number" name="vek" required></td></tr>
				<tr><td>Heslo<input type="text" name="heslo" required></td></tr>
				<tr><td><input type="submit" value="Pridať"></td></tr>
			</table>
		</div>
		
	</form>
</div>