<div id="new_work">
	<?php if ($success != "") :?>
		<p><?= $success ?></p>
	<?php endif; ?>
	<form method="POST" action="buddies/new_work" id="new_work">
		<input type="hidden" name="nazov_familie" value="<?php echo $don->getNazovFamilie();?>" />
		<p>Špecifické meno úlohy<input type="text" name="specificke_meno" required></p>
		<p>Popis činnosti<input type="text" name="popis_cinnosti" required></p>
		<p>Vykonávateľ
			<select>
				<option value="" selected=""></option>
				<option value="zelenac">Zelenáč</option>				
				<option value="uklizec">Zametač</option>
				<option value="sofer">Šofér</option>
				<option value="kapsar">Zlodej</option>
				<option value="vymahac">Vymáhač</option>
				<option value="snajper">Snajper</option>
			</select>
		</p>
		<p>
			Zadávateľ<input type="radio" name="zadavatel_don" value="<?php echo $don->getRodneCislo();?>" required>Don
			<?php if ($don->getAliancia() != NULL) :?>
				<input type="radio" name="zadavatel_aliancia" value="<?php echo $don->getAliancia();?>" required>Aliancia
			<?php endif; ?>
		</p>
		<p>GPS súradnice miesta<input type="text" name="heslo" required></p>
		<p>
			Hodnosť<!-- <input type="text" name="hodnost" required> -->
			<select>
				<option value="" selected=""></option>
				<option value="zelenac">Zelenáč</option>				
				<option value="uklizec">Zametač</option>
				<option value="sofer">Šofér</option>
				<option value="kapsar">Zlodej</option>
				<option value="vymahac">Vymáhač</option>
				<option value="snajper">Snajper</option>
			</select>
		</p>
		<p>
			Pokrvná väzba<input type="radio" name="pokrvna_vazba" value="ano" required>áno
			<input type="radio" name="pokrvna_vazba" value="ne" required>nie
		</p>
		<input type="submit" value="Pridať">
	</form>
</div>