<div id="new_work">
	<?php if ($success != "") :?>
		<p><?= $success ?></p>
	<?php endif; ?>
	<form method="POST" action="todolist/new_work" id="new_work">
		<input type="hidden" name="nazov_familie" value="<?php echo $don->getNazovFamilie();?>" />
		<p>Špecifické meno úlohy<input type="text" name="specificke_meno" required></p>
		<p>Popis činnosti<input type="text" name="popis_cinnosti" required></p>
		<p>
			Zadávateľ<input type="radio" name="zadavatel" value="<?= $don->getRodneCislo();?>" required>Don
			<?php if ($don->getAliancia() != NULL) :?>
				<input type="radio" name="zadavatel" value="<?= $don->getAliancia();?>" required>Aliancia
			<?php endif; ?>
		</p>	
		<p>Vykonávateľ
			<input type="text" list="clenovia" name="vykonavatel">
			<datalist id="clenovia" autocomplete="off">
				<select>
					<option value="" selected=""></option>
					<?php foreach($zoz_vykon as $zoznam) : ?>
						<option value="<?= $zoznam["rodne_cislo"]?>"><?= $zoznam["meno"] . " " . $zoznam["priezvisko"]?></option>
					<?php endforeach; ?>
				</select>				
			</datalist>
		</p>
		
		<p>GPS súradnice miesta
			<input type="text" list="uzemie" name="gps_miesta" required>
			<datalist id="uzemie" autocomplete="off">
				<select>
					<option value="" selected=""></option>
					<?php foreach($uzemia as $miesto) : ?>
						<?php if ($miesto["gps"] != "admin") :?>
							<option value="<?= $miesto["gps"]?>"><?= $miesto["hodnota"]?></option>
						<?php endif; ?>
					<?php endforeach; ?>
				</select>				
			</datalist>
		</p>
		<input type="submit" value="Pridať">
	</form>
</div>