<div id="todolist" action="todolist">
	<?php if($_SESSION["typ"] != 0) : //DON alebo ADMIN?>
		<form method="POST" action="todolist/new_work" id="new_work">
			<input type="submit" value="Zadať novú úlohu">
		</form>
	<?php endif; ?>
	<?php if(empty($ulohy)) : ?>
		<tr><td>Žiadne zadané úlohy</td><tr>
	<?php endif; ?>
	<?php foreach($ulohy as $uloha) : ?>
		<p><?php if ($uloha["zadavatel_don"] != NULL) echo "Don:"; else echo "Aliancia:" ?></p>
		<p>Meno: <?= $uloha["specificke_meno"] ?></p>
		<p>Popis činnosti: <?= $uloha["popis_cinnosti"] ?></p>
		<p>Vykonávateľ: <?= $uloha["vykonavatel"] ?></p>
		<p>Zadávateľ: <?php if ($uloha["zadavatel_don"] != NULL) echo $uloha["zadavatel_don"]; else echo $uloha["zadavatel_aliancia"] ?></p>
		<p>Miesto: <?= $uloha["gps_miesta"] ?></p>
		<?php if($uloha["cas_zaciatku"] == NULL) : ?>
			<p>Čas začiatku: </p>
			<form method="POST" action="todolist/zacat">
				<input type="datetime-local" name="cas_zaciatku" required>
				<input type="hidden" name="specificke_meno" value="<?= $uloha["specificke_meno"] ?>">
				<input type="submit" value="Začať úlohu">
			</form>
		<?php else :?>
			<p>Čas začiatku: <?= $uloha["cas_zaciatku"] ?></p>	
			<?php if ($uloha["cas_konca"] == NULL) :?>
			<form method="POST" action="todolist/ukoncit">	
				<p>Čas konca: </p>
				<input type="datetime-local" name="cas_konca" required>
				<input type="hidden" name="specificke_meno" value="<?= $uloha["specificke_meno"] ?>">		
				<p>Úspesnosť: 
					<input type="radio" name="uspesnost" value="ano" required>áno
					<input type="radio" name="uspesnost" value="ne" required>nie
				</p>
				<p>Komentár: <input type="text" name="komentar" required></p>
				<input type="submit" value="Ukončiť úlohu">		
			</form>
			<?php else : ?>
				<p>Čas konca: <?= $uloha["cas_konca"] ?></p>
				<p>Úspesnosť: <?= $uloha["uspesnost"] ?></p>
				<p>Komentár: <?= $uloha["komentar"] ?></p>
			<?php endif;?>				
		<?php endif;?>	
	<?php endforeach; ?>
</div>