<div id="todolist" action="todolist">
	<?php if($_SESSION["typ"] != 0) : //DON alebo ADMIN?>
		<form method="POST" action="todolist/new_work" id="new_work">
			<table>
				<th><input type="submit" value="Zadať novú úlohu"></th>
			</table>	
		</form>
	<?php endif; ?>
	<?php if(empty($ulohy)) : ?>
		<tr><td>Žiadne zadané úlohy</td><tr>
	<?php endif; ?>
	<?php foreach($ulohy as $uloha) : ?>
		<?php if($uloha["specificke_meno"] != "admin") : ?>
			<div id="uloha">
				<table>
					<tr><td><?php if ($uloha["zadavatel_don"] != NULL) echo "Zadano Donem"; else echo "Zadano Alianciou" ?></td><td></td></tr>
					<tr><td>Meno: </td><td> <?= $uloha["specificke_meno"] ?></td></tr>
					<tr><td>Popis činnosti: </td><td> <?= $uloha["popis_cinnosti"] ?></td></tr>
					<tr><td>Vykonávateľ: </td><td> <?= $uloha["vykonavatel"] ?></td></tr>
					<tr><td>Zadávateľ: </td><td> <?php if ($uloha["zadavatel_don"] != NULL) echo $uloha["zadavatel_don"]; else echo $uloha["zadavatel_aliancia"] ?></td></tr>
					<tr><td>Miesto: </td><td> <?= $uloha["gps_miesta"] ?></td></tr>
					<?php if($uloha["cas_zaciatku"] == NULL) : ?>
						<tr><td>Čas začiatku: </td></tr>
						<form method="POST" action="todolist/zacat">
							<input type="datetime-local" name="cas_zaciatku" required>
							<input type="hidden" name="specificke_meno" value="<?= $uloha["specificke_meno"] ?>">
							<tr> <td></td> <td><input type="submit" value="Začať úlohu"> </td></tr>
						</form>
					<?php else :?>
						<tr><td>Čas začiatku: </td><td> <?= $uloha["cas_zaciatku"] ?></td></tr>
						<?php if ($uloha["cas_konca"] == NULL) :?>
							<form method="POST" action="todolist/ukoncit">	
								<tr><td>Čas konca: </td><td>
								<input type="datetime-local" name="cas_konca" required></td></tr>
								<input type="hidden" name="specificke_meno" value="<?= $uloha["specificke_meno"] ?>">		
								<tr><td>Úspesnosť: </td><td>
									<input type="radio" name="uspesnost" value="ano" required>áno
									<input type="radio" name="uspesnost" value="ne" required>nie
								</td></tr>
								<tr><td>Komentár: </td><td> <input type="text" name="komentar" required></td></tr>
								<tr> <td></td> <td><input type="submit" value="Ukončiť úlohu">	</td></tr>	
							</form>				
						<?php else : ?>
							<tr><td>Čas konca: </td><td><?= $uloha["cas_konca"] ?></td></tr>
							<tr><td>Úspesnosť: </td><td><?= $uloha["uspesnost"] ?></td></tr>
							<tr><td>Komentár: </td><td><?= $uloha["komentar"] ?></td></tr>
						<?php endif;?>	
				</table>
			</div>				
			<?php endif;?>	
		<?php endif; ?>
	<?php endforeach; ?>
</div>